name: gh-pages-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate index.html
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang=\"th\">" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset=\"UTF-8\">" >> index.html
          echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> index.html
          echo "  <title>Index Page</title>" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "  <h1>รายการไฟล์</h1>" >> index.html
          echo "  <ul>" >> index.html
          ls -1tr ${{ github.workspace }}/pages/* | while read file; do
            file_name=$(basename "$file")
            file_date=$(git log -1 --format="%cI" "$file")
            echo "    <li><a href=\"pages/$file\">$file_name</a> ($file_date)</li>" >> index.html
          done
          echo "  </ul>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
