# This is a basic workflow that is manually triggered

name: gh-pages-deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write      # to deploy to Pages
  id-token: write 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  gh-pages-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - uses: actions/checkout@v4
      - name: Generate index.html
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html lang=\"th\">" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset=\"UTF-8\">" >> index.html
          echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> index.html
          echo "  <title>Index Page</title>" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "  <h1>รายการไฟล์</h1>" >> index.html
          echo "  <ul>" >> index.html
          ls -1 pages/* | sort -r | while read file; do
            file_name=$(basename "$file")
            file_date=$(git log -1 --format="%cI" "$file")
            file_time=$(git log -1 --format="%cI" "$file" | cut -d' ' -f2)
            echo "    <li><a href=\"$file\">$file_name</a> ($file_date $file_time)</li>" >> index.html
          done
          echo "  </ul>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
